version: 2
updates:
  # app
  - package-ecosystem: "npm"
    directory: "function-deployer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "function-invoker"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "report-log-processor"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "function-trigger-invoker"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "function-trigger-deployer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "result-builder"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "s3-uploader"
    schedule:
      interval: "monthly"

  # runtimes
  - package-ecosystem: "nuget"
    directory: "s3-uploader/runtimes/dotnet6/src"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "s3-uploader/runtimes/rust_on_provided_al2"
    schedule:
      interval: "daily"
