name: deploy to aws

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'region on which you want to deploy'
        type: choice
        options:
          - ap-southeast-2
        required: true
      lambdaPerfEnv:
        description: 'environment on which you want to deploy'
        type: choice
        options:
          - production
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install dependencies
        run: |
          cd function-deployer && yarn install
          cd ../function-invoker && yarn install
          cd ../function-trigger-invoker && yarn install
          cd ../result-builder && yarn install
          cd ../report-log-processor && yarn install
      - name: install Serverless Framework
        run: sudo yarn global add serverless@^3.27.0 --prefix /usr/local
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          mask-aws-account-id: true
      - name: deploy
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
          LAMBDA_PERF_ENV: ${{ inputs.lambdaPerfEnv }}
        run: |
          sls deploy --force
