name: build and upload artifacts in S3

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'region on which you want to deploy'
        type: choice
        options:
          - ap-southeast-2
        required: true
      architecture:
        description: 'architecture'
        type: choice
        options:
          - x86_64
          - arm64
        required: true

jobs:
  build-upload:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.region }}
          mask-aws-account-id: true
      - name: build and deploy
        env:
          ARCHITECTURE: ${{ inputs.architecture }}
        run: |
          cd s3-uploader
          yarn install
          node app.mjs
